services:
  - type: web
    name: ssbbank-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: URL_DATABASE
        value: jdbc:postgresql://dpg-d0l7k0t6ubrc73brloog-a.oregon-postgres.render.com:5432/bankdb_pkem
      - key: DATABASE_USERNAME
        value: ssbbankuser
      - key: DATABASE_PASSWORD
        value: PVY0zTvxQbqEznJbQKZFVeUVOk8iVO9c
      - key: PORT_NUMBER
        value: 8080
      - key: JWT_SECRET
        value: X2sUcnmqBZpkc5V4oNR2dt/5KdaZBslU6nlVJDgQaEs=
      - key: CORS_ALLOWED_ORIGINS
        value: https://ssbproject.netlify.app

