spring:
  application:
    name: sistemabancario
  datasource:
    url: jdbc:postgresql://${URL_DATABASE}:5432/bank
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5500}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

server:
  port: ${PORT_NUMBER:8080}