spring:
  application:
    name: sistemabancario
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

server:
  port: 8081